version: '3'

services:
  postgresdb:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_PASSWORD: password
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/1-db.sql

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge